# -*- coding: utf-8 -*-
"""Cash Flow Network

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107uiTj7dKe9I3jmB-1PmSfGWnF3Mf-ju
"""

from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import io
import base64
from starlette.responses import JSONResponse

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Change this to the specific frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.post("/upload/")
async def upload_csv(file: UploadFile = File(...)):

    df = pd.read_csv(file.file)
    return {"columns": df.columns.tolist()}


@app.post("/generate-graph/")
async def generate_cashflow_graph(
    file: UploadFile = File(...),
    from_col: str = Form(...),
    to_col: str = Form(...),
    amount_col: str = Form(...),
):


    df = pd.read_csv(file.file)

    if not {from_col, to_col, amount_col}.issubset(df.columns):
        return JSONResponse(content={"error": "Invalid column mappings"}, status_code=400)

    G = nx.DiGraph()

    for _, row in df.iterrows():
        G.add_edge(row[from_col], row[to_col], weight=row[amount_col])

    pos1 = nx.spring_layout(G, seed=42)
    pos2 = nx.shell_layout(G)

    node_colors = {}
    for node in G.nodes():
        if "Politician" in node:
            node_colors[node] = "red"
        elif "Corporate" in node:
            node_colors[node] = "blue"
        elif "Lobbying" in node:
            node_colors[node] = "green"
        else:
            node_colors[node] = "orange"

    node_color_list = [node_colors.get(node, "gray") for node in G.nodes()]

    edge_widths = [G[u][v]["weight"] / 20000 for u, v in G.edges()]

    def generate_graph(pos):
        plt.figure(figsize=(12, 8))
        nx.draw(
            G, pos, with_labels=True, node_color=node_color_list, node_size=2000,
            font_size=10, font_weight="bold", arrows=True, width=edge_widths, edge_color="gray"
        )
        edge_labels = nx.get_edge_attributes(G, "weight")
        nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8)

        buf = io.BytesIO()
        plt.savefig(buf, format="png")
        plt.close()

        buf.seek(0)
        return base64.b64encode(buf.getvalue()).decode("utf-8")

    img1_base64 = generate_graph(pos1)
    img2_base64 = generate_graph(pos2)

    return {
        "spring_layout": img1_base64,
        "shell_layout": img2_base64,
    }